services:
  web:
    build: .
    ports:
      - "5173:5173" # dev
      - "4173:4173" # production
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MODE=${MODE}
      - PORT=${PORT}